APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:qbxEMorMDL872z29Uo2lzc5S2DVKLL2xyN71hIKBSp4=
APP_DEBUG=true
APP_TIMEZONE=UTC
APP_URL=http://localhost

APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file
# APP_MAINTENANCE_STORE=database

PHP_CLI_SERVER_WORKERS=4

BCRYPT_ROUNDS=12

# PDF_API_URL=http://localhost:3000

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

# --- Keep only ONE DB_HOST line ---
DB_CONNECTION=mysql
DB_HOST=127.0.0.1   # Use 127.0.0.1 for TCP/IP connection
DB_PORT=3306
DB_DATABASE=enhance_cv_builder
DB_USERNAME=root
DB_PASSWORD=

SESSION_DRIVER=file
SESSION_LIFETIME=120
SESSION_ENCRYPT=true  # Changed to true
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database

# Removed Redis block
# Remove Cache
# CACHE_STORE=file
CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1 #you dont have this, so delete this
# Remove Memcache as well

# REDIS_CLIENT=phpredis
# REDIS_HOST=127.0.0.1
# REDIS_PASSWORD=null
# REDIS_PORT=6379

BROWSERSHOT_CHROMIUM_PATH=C:\Chromium\chrome-win\chrome.exe

MAIL_MAILER=log
MAIL_SCHEME=null
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

GOOGLE_CLIENT_ID=345059797459-rdm0tcf04qdji5d1bk5upb3uglc6n9gi.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=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
GOOGLE_REDIRECT_URI= http://127.0.0.1:8000/callback/google

VITE_APP_NAME="${APP_NAME}"
